### PR TITLE
Attempt at adding cosine similarity metric

### PR DESCRIPTION
**Pull request by jlevy44**
Hopefully I'm not too far off.  Let's merge when we're both feeling confident about the changes! Thanks!

### CODE REVIEW

**Comment by jlevy44** [comment]
#26 

I did not test this implementation. Been swamped with some other works, but I can test when the code has been shaped a bit more.

**Comment by rusty1s** [comment]
Looks good so far :)

I suggest the following changes:
* `dotProduct` and `calc_norm` should actually take in `scalar_t` values using templates. And maybe rename them to `dot` and `norm`?
* You said that the `sklearn` implementation is slower, so I think we should branch here dependent on which metric is used.
* `sklearn` needs to be a dependency in `setup.py`.

**Comment by jlevy44** [comment]
Ok, just updated a bit, still need your help to test and finish. Thanks!

**Comment by rusty1s** [comment]
Great, will try to merge tomorrow.

**Comment by jlevy44** [comment]
Awesome let me know how it goes.

**Comment by rusty1s** [comment]
Well, I cleaned up the code. It was kinda buggy, didn't you test it? In addition, there is no sklearn kNN implementation for the cosine distance, so currently I raise a `NotImplementedError` for the cpu version.

**Pull request merged**
