### PR TITLE
FPS with one ratio for each point cloud

### PR DESCRIPTION
**Pull request by justanhduc**
In some scenario, it would be nice to be able to sample with different ratios for different point sets. However, `typing` and `jit` make it quite difficult to make the function accept both `float` and `torch.Tensor`. What do you think about this PR?

### CODE REVIEW

**Comment by rusty1s** [comment]
Thanks, I like it :) one minor request: It would be great if we can also support the old interface, so that ratio can either be a float or a tensor.

**Comment by justanhduc** [comment]
Thanks. Supporting both is what's bugging me so far. [`torch.jit.script` does not support `Union[float, Tensor]`](https://discuss.pytorch.org/t/will-torch-script-support-typing-union/61720/2), so any attempt to duck type `float` and `Tensor` will make the test fail. Do you have any idea?

**Comment by rusty1s** [comment]
You can use overloads to achieve that, see [here](https://github.com/rusty1s/pytorch_geometric/blob/a6a7ab92e24660582d4d1ff8a54b19c2bf5d211a/torch_geometric/nn/conv/gcn_conv.py#L16-L31).

**Comment by justanhduc** [comment]
Nice! I will write the interface again and push some tests as well to make the PR complete.

**Comment by justanhduc** [comment]
Hi @rusty1s. Sorry for this very late response. I fixed the overloading issue and merged with the current branch. Could you plz take a look?

**Comment by rusty1s** [comment]
Thanks, I will try to merge on monday.

**Comment by rusty1s** [comment]
Thanks once again :)

**Pull request merged**
